const fs=require('fs'),vm=require('vm'),assert=require('assert');
const sandbox={window:null,Date,Math,localStorage:{getItem(){return null},setItem(){}},YK_WORLD:{start:[384,500],hub:[384,500],revision:88,places:{village:{}},migratePosition:p=>p||[384,500]}};sandbox.window=sandbox;vm.createContext(sandbox);
for(const f of ['data','equipment','save'])vm.runInContext(fs.readFileSync('js/'+f+'.js','utf8'),sandbox);
const E=sandbox.YK_EQUIPMENT,Save=sandbox.YK_SAVE,checks=[];
function check(name,fn){fn();checks.push(name)}
check('catalog entries have attainable sources and correct slots',()=>{for(const [id,i] of Object.entries(E.items)){assert(E.slots[i.slot]);assert(i.source);assert(i.price===null||i.price>=0);assert(Object.values(E.starters).includes(id)||i.price>0||E.chests.some(c=>c.item===id)||Object.values(E.drops).some(d=>d.id===id),id)}});
check('retired outfits migrate without losing progress, money, relics or stats',()=>{for(const outfit of ['basewear','light','white','navy','yukata','demon']){const s=Save.migrate({outfit,lv:9,gold:321,atk:38,def:12,quest:4,relics:{oni:2},equippedRelic:'oni',chests:{oldChest:true}});assert.equal(s.outfit,'normal');assert.equal(s.lv,9);assert.equal(s.gold,321);assert.equal(s.atk,38);assert.equal(s.def,12);assert.equal(s.quest,4);assert.equal(s.relics.oni,2);assert.equal(s.equippedRelic,'oni');assert(s.chests.oldChest);assert.equal(E.bonus(s,'atk'),0)}});
check('stardust stays selected and migration is idempotent',()=>{const s=Save.migrate({outfit:'stardust'});E.grant(s,'silver_staff');E.equip(s,'weapon','silver_staff');const once=Save.migrate(s),twice=Save.migrate(once);assert.equal(once.outfit,'stardust');assert.equal(JSON.stringify(once),JSON.stringify(twice));assert.equal(once.equipment.weapon,'silver_staff')});
check('invalid or unowned equipment cannot grant stats',()=>{const s=Save.migrate({...Save.fresh(),equipmentInventory:{gold_staff:1,garbage:100},equipment:{weapon:'love_staff',head:'gold_staff'},chests:null});assert.equal(s.equipment.weapon,null);assert.equal(s.equipment.head,null);assert.equal(E.bonus(s,'atk'),0);assert(!('garbage' in s.equipmentInventory));assert.deepEqual(JSON.parse(JSON.stringify(s.chests)),{})});
check('purchases respect progression, funds and inventory capacity atomically',()=>{const s=Save.fresh();s.gold=1000;assert(E.buy(s,'gold_staff'));assert.equal(s.gold,1000);assert.equal(E.buy(s,'short_blade'),null);assert.equal(s.gold,935);assert.equal(s.equipmentInventory.short_blade,1);s.gold=0;assert(E.buy(s,'short_blade'));assert.equal(s.equipmentInventory.short_blade,1);s.gold=1000;s.equipmentInventory.short_blade=99;assert(E.buy(s,'short_blade'));assert.equal(s.gold,1000)});
check('equipment changes only the correct slot and appearance never changes',()=>{const s=Save.fresh();E.grant(s,'short_blade');assert(!E.equip(s,'body','short_blade'));assert(!E.equip(s,'weapon','gold_staff'));assert(E.equip(s,'weapon','short_blade'));assert.equal(E.bonus(s,'atk'),4);assert.equal(s.outfit,'normal');assert.equal(s.weapon,'わきざし');assert(E.equip(s,'weapon',null));assert.equal(E.bonus(s,'atk'),0)});
check('sale preserves equipped last copy and unique treasures',()=>{const s=Save.fresh();E.grant(s,'short_blade');E.equip(s,'weapon','short_blade');assert(E.sell(s,'short_blade'));E.grant(s,'short_blade');const gold=s.gold;assert.equal(E.sell(s,'short_blade'),null);assert.equal(s.gold,gold+32);assert.equal(s.equipmentInventory.short_blade,1);E.grant(s,'love_staff');assert(E.sell(s,'love_staff'))});
check('every chest grants exactly once and survives save migration',()=>{for(const c of E.chests){let s=Save.fresh();Object.assign(s,{area:c.area,x:c.x,y:c.y,quest:6});assert(E.open(s,c.id).ok);assert.equal(s.equipmentInventory[c.item],1);s=Save.migrate(s);assert(!E.open(s,c.id).ok);assert.equal(s.equipmentInventory[c.item],1)}});
check('distant, sealed and full-inventory chests cannot be consumed',()=>{const c=E.chests[4],s=Save.fresh();assert(!E.open(s,c.id).ok);Object.assign(s,{area:c.area,x:c.x,y:c.y,quest:0});assert(!E.open(s,c.id).ok);assert(!s.chests[c.id]);s.quest=6;s.equipmentInventory[c.item]=99;assert(!E.open(s,c.id).ok);assert(!s.chests[c.id])});
check('all enemy drop tables use bounded probability and known items',()=>{for(const [enemy,d] of Object.entries(E.drops)){const s=Save.fresh();assert(d.chance>0&&d.chance<1);const n=s.equipmentInventory[d.id]||0;assert.equal(E.drop(s,enemy,()=>1),null);assert.equal(E.drop(s,enemy,()=>0),d.id);assert.equal(s.equipmentInventory[d.id],n+1);s.equipmentInventory[d.id]=99;assert.equal(E.drop(s,enemy,()=>0),null)}});
console.log(JSON.stringify({passed:checks.length,checks,items:Object.keys(E.items).length,chests:E.chests.length},null,2));
