// Isolated Chromium acceptance: traversal, doors, migration, NPC services and animated river.
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert');
const {chromium}=require(require.resolve('playwright',{paths:[process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES||process.cwd()]}));
const root=path.resolve(__dirname,'..'),out=path.join(__dirname,'results/autotile');fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{const name=decodeURIComponent(req.url.split('?')[0]),file=path.join(root,name==='/'?'index.html':name);if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.webp':'image/webp'})[path.extname(file)]||'application/octet-stream');let data=fs.readFileSync(file);if(name==='/js/game.js')data=Buffer.from(data.toString().replace(/\}\)\(\);\s*$/, 'window.__qaEval=code=>eval(code);})();'));res.end(data);});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true});try{
 for(const height of [852,568]){
 const page=await browser.newPage({viewport:{width:393,height},isMobile:true,hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>window.YK_LANDSCAPE?.ready());const run=code=>page.evaluate(code=>window.__qaEval(code),code);
 await run('state(YK_SAVE.fresh());$("title").classList.remove("show");busy=false;');
 const guides=await run('YK_WORLD.guides');assert.equal(guides.length,5);
 for(const guide of guides){const approach=await run(`(()=>{const g=YK_WORLD.guides[${guide.id}];return [[32,32],[32,0],[0,32],[-32,0],[0,-32]].map(([x,y])=>[g.x+x,g.y+y]).find(([x,y])=>YK_WORLD.walkable(x,y));})()`);assert(approach,'guide reachable '+guide.id);
 await run(`S.area="field";S.x=${approach[0]};S.y=${approach[1]};S.quest=2;busy=false;action();`);assert.equal(await page.locator('#speaker').textContent(),guide.name);assert((await page.locator('#dialogText').textContent()).includes('潮平'));assert.equal(await run('S.quest'),2);await run('while($("dialog").classList.contains("show"))nextDialog();');}
 await run('S.quest=6;guideTalk();');assert((await page.locator('#dialogText').textContent()).includes('一区切り'));await run('while($("dialog").classList.contains("show"))nextDialog();');
 await run('S.x=768;S.y=1190;S.area="village";S.hp=40;S.mp=10;');await page.locator('#bookBtn').tap();const pos=await run('[S.x,S.y]');await page.locator('#down').tap();assert.equal(await run('fieldCursor'),2);await page.locator('#ok').tap();assert.equal(await run('S.hp'),72);assert.equal(await run('S.mp'),7);assert.deepEqual(await run('[S.x,S.y]'),pos);
 await page.locator('#bookBtn').tap();const box=await page.locator('.commandWindow').boundingBox(),pad=await page.locator('#pad').boundingBox();assert(box.y+box.height<=pad.y,'menu clear of A/B');await page.screenshot({path:path.join(out,'commands-'+height+'.png')});await page.locator('#cancel').tap();assert(!await run('busy'));
 await page.locator('#bookBtn').tap();await page.locator('[data-field-command="items"]').tap();const potions=await run('S.potions');await page.locator('#fieldHerb').tap();assert.equal(await run('S.potions'),potions-1);assert.equal(await run('S.hp'),100);await page.locator('#fieldHerb').tap();assert.equal(await run('S.potions'),potions-1);await page.locator('#cancel').tap();assert(!await run('busy'));await run('S.x=548;S.y=456;S.dir="u";S.walk=1000;S.harvests={};S.vegetables={};window.__oldRandom=Math.random;Math.random=()=>0;');
 await page.locator('#bookBtn').tap();await page.locator('[data-field-command="search"]').tap();assert((await page.locator('#dialogText').textContent()).includes('だいこん'));assert.equal(await run('S.vegetables.radish'),1);await page.locator('#dialogNext').tap();
 await run('S=window.gameState=YK_SAVE.loadAuto();inspectObject();');assert((await page.locator('#dialogText').textContent()).includes('育ちかけ'));assert.equal(await run('S.vegetables.radish'),1);await page.locator('#dialogNext').tap();
 await run('S.walk+=160;Math.random=()=>.9;inspectObject();');assert((await page.locator('#dialogText').textContent()).includes('ないよう'));assert.equal(await run('S.vegetables.radish'),1);await page.locator('#dialogNext').tap();
 await run('S.hp=50;Math.random=window.__oldRandom;');await page.locator('#bookBtn').tap();await page.locator('[data-field-command="items"]').tap();await page.locator('[data-vegetable="radish"]').tap();assert.equal(await run('S.hp'),68);assert.equal(await run('YK_SAVE.loadAuto().vegetables.radish'),0);await page.locator('#cancel').tap();
 await run('S.x=672;S.y=686;S.dir="u";inspectObject();');assert((await page.locator('#dialogText').textContent()).includes('井戸'));await page.locator('#dialogNext').tap();
 assert.deepEqual(errors,[]);await page.close();console.log('guides and commands '+height+': stage-aware hints, no quest mutation, D-pad/A/B, healing cost and safe layout');
 }
 }finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
